name: create-release

permissions:
  contents: write
          
on:
  workflow_run:
    workflows: [run-integration-test]
    types:
      - completed
    branches:
        - dev

jobs:
  create-release:
    name: Create release job
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Generate next tag
        id: gen_next_tag
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const { data: tags } = await github.rest.git.listMatchingRefs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/'
            });
            
            let last_tag = ["v0","0","0"];
            if (tags.length) {
                last_tag = tags[tags.length - 1].ref.split("/")[2].split(".");
            }
            return last_tag.slice(0,2).concat(+last_tag[2]+1).join(".");

      - name: Generate release
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const next_tag = ${{steps.gen_next_tag.outputs.result}}

            await github.rest.repos.createRelease({
               owner: context.repo.owner,
               repo: context.repo.repo,
               tag_name: next_tag,
               target_commitish: "dev"
            });
            